### ISSUE TITLE
Discussion: Infer suffix from base class name

### ISSUE THREAD

**Issue by mberr** [cthoyt/class-resolver#3]
If base class defines some interface, e.g. `Similarity`, the child classes often use this as suffix, e.g. `DotProductSimilarity` and  `CosineSimilarity`. In such case, using the base class as a default suffix may be useful.

Thus, I propose to extend `Resolver.from_subclasses` to use the (normalized) name of the base class as suffix, if None is provided. To disable this, a user could explicitly pass the empty string.

**Comment by cthoyt** [comment]
I'm not sure what I think about this. There are definitely some use cases where the base class doesn't have the right pattern, but I guess you're right that it's less common. So I could get behind the proposal
