### ISSUE TITLE
Replace use of pkg_resources with importlib

### ISSUE THREAD

**Issue by cmungall** [cthoyt/class-resolver#52]
[pkg_resources is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html)

this is currently used for discovery:

https://github.com/cthoyt/class-resolver/blob/ca2bd8a384df26b3aac6270756f9cd32f528093a/src/class_resolver/base.py#L19

We are experiencing some issues regarding the behavior of class-resolver and different versions of setuptools, @hrshdhg will report shortly. But it may be easiest to remove uses of deprecated packages

**Comment by cthoyt** [comment]
happy to accept a PR for this if it's py37+ compatible!
